### ISSUE TITLE
[FEATURE REQUEST] Add a pseudo-icon (blank or black)

### ISSUE THREAD

**Issue by andrewjswan** [lubeda/EspHoMaTriXv2#117]
# Feature Request

### Describe the solution / feature you'd like

Add a pseudo-icon (blank or black), this will allow you to display the date, day of the week on an empty background, and save memory, will not have to add it as an icon. It can be labeled as -1, and if the icon is equal to -1, then just do not draw it.

### Describe alternatives you've considered

Right now I'm using code like this, but it steals one icon and steals memory. 

```
ehmtxv2:
  icons: 
    - id: black
      lameid: 2758
    - id: white
      lameid: 499

  on_start_running:
     then:
       lambda: |-
          id(rgb8x32)->icon_date("black|weekday", 1440, 5, true); // K
```
