### ISSUE TITLE
[BUG] Icon Screens, Screen Time... not honored?

### ISSUE THREAD

**Issue by darkpoet78** [lubeda/EspHoMaTriXv2#12]
# Bug report

Calling various icon screens from Home Assistant, it would appear that the screen times are not being honored.  I'd like to keep my icon screens short but I can see in the code that the default is 5 seconds and shortening the time in Home Assistant doesn't change that...

```
      - service: esphome.pixelclock_yellow_icon_screen
        data:
          default_font: true
          icon_name: >-
            weather_{{ states('sensor.openweathermap_condition')|replace("-",
            "_") }}
          text: "{{ states('sensor.openweathermap_temperature')|round(1) }}°"
          lifetime: 5
          screen_time: 3
          r: 192
          g: 192
          b: 192
```

I also tried this in my YAML and it doesn't lengthen the default clock screen:

```
esphome:
  comment: "EHMTXv2 from LuBeDa"
  name: $devicename 
  on_boot:
    then:      
      - ds1307.read_time:
      - delay: 30s
      - lambda: |-
          id(rgb8x32)->set_clock_time(30);
```

So far, I fixed this by simply doing this in my Home Assistant (deleting the default clock screen and inserting my own):
```
  - service: esphome.pixelclock_yellow_del_screen
    data:
      icon_name: "*"
      mode: 2
  - service: esphome.pixelclock_yellow_clock_screen
    data:
      default_font: false
      lifetime: 5
      screen_time: 20
      r: 64
      g: 128
      b: 255
```

Sidenote that I miss one of the old features of clock intervals from v1... that the default clock screen would display a minimum of every x seconds (that was clock intervals)... this made it easier for me to force every 2nd screen to be the clock (ie. Clock, Weather, Clock, Inside Temperature, Clock, Humidity, etc.)  You know what I mean?  It easy enough just to change the clock interval to 5 seconds, info screens 5 seconds, forcing my preferred behavior... I can ignore losing that if I can speed through all my info screens...
