### ISSUE TITLE
[WIP] Bitmap Stack screen

### ISSUE THREAD

**Issue by andrewjswan** [lubeda/EspHoMaTriXv2#139]
# Work In Progress

### Describe the solution / feature you'd like

A screen that allows you to display from 1 to 64 icons described in the configuration.
I don’t know what kind of case it can be used in, but I was interested in trying out what it would look like, and when I saw it live, I realized that it was funny, and even possibly useful.

### Additional context

I don’t have a lot of videos coming out, but maybe one of those who have already tried it will publish what it looks like.

**Comment by andrewjswan** [comment]
Usage example:
```
service: esphome.ulanzi_bitmap_stack
data:
  icons: icon1,icon2
  lifetime: 1
  screen_time: 20
```

```
service: esphome.ulanzi_bitmap_stack
data:
  icons: icon1,icon2,icon3|two
  lifetime: 1
  screen_time: 20
```
