### ISSUE TITLE
[BUG] rainbow_icon_text_screen does not showing text

### ISSUE THREAD

**Issue by idodov** [lubeda/EspHoMaTriXv2#169]
When I use service:
```
service: esphome.ulanzi_rainbow_icon_text_screen
data:
  default_font: true
  icon_name: music
  text: this is an example text
  lifetime: 1
  screen_time: 5
```
The screen shows the icon, but not the text string, when the icon is the last on the yaml list.
Also there is no rainbow effect when trying other icon names.

for exmaple, the last icon `music `making the bug.
```
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: "%H:%M:%S"
  date_format: "%d.%m"
  week_start_monday: false 
  show_dow: true
  show_seconds: false
  default_font_id: default_font
  default_font_yoffset: 6
  special_font_id: special_font
  icons: 
    - id: alert
      lameid: 16701
    - id: vol
      lameid: 56196
    - id: timer
      lameid: 42893
    - id: error
      lameid: 40530
    - id: tv
      lameid: 10972
    - id: oref_1
      lameid: 49151
    - id: oref_2
      lameid: 555
    - id: oref_3
      lameid: 170     
    - id: oref_4
      lameid: 23577
    - id: oref_5
      lameid: 13267
    - id: oref_6
      lameid: 31805
    - id: oref_7
      lameid: 19622
    - id: oref_13
      lameid: 18391
    - id: sleep8x32
      url: https://user-images.githubusercontent.com/16407309/224850723-634c9b2d-55d9-44f2-9f93-765c0485b090.gif 
    - id: weather_clear_night
      lameid: 53383
    - id: weather_sleet
      lameid: 12198
    - id: weather_clear_day
      lameid: 12192
    - id: weather_partly_cloudy_day
      lameid: 51452
    - id: weather_partly_cloudy_night
      lameid: 51412
    - id: weather_cloudy
      frame_duration: 192
      lameid: 25991
    - id: weather_exceptional
      lameid: 16754
    - id: weather_fog
      lameid: 52167
    - id: weather_hail
      lameid: 53288
    - id: weather_lightning
      lameid: 23713
    - id: weather_lightning_rainy
      lameid: 49299
    - id: weather_partlycloudy
      frame_duration: 210
      lameid: 22160
    - id: weather_pouring
      lameid: 49300
    - id: weather_rain
      lameid: 26565
    - id: weather_snow
      lameid: 2289
    - id: weather_snowy_rainy
      lameid: 49301
    - id: weather_sunny
      lameid: 11201
    - id: weather_wind
      lameid: 15618
    - id: weather_windy_variant
      lameid: 15618
    - id: weather_cloudy_night
      lameid: 12195
    - id: tidal
      lameid: 48637
    - id: apple
      lameid: 49294
    - id: spotify
      lameid: 41981
    - id: radio
      lameid: 99
    - id: music 
      lameid: 5865
```
