### ISSUE TITLE
Character not being rendered correctly even it's in the font

### ISSUE THREAD

**Issue by Alex-joomla** [lubeda/EspHoMaTriXv2#189]
# Question

I call a service node in node red to add a Icon_screen:

```
{
    "icon_name": "dishwasher",
    "text": "{{payload}}",
    "lifetime": "1",
    "screen_time": "1",
    "r": 255,
    "g": 255,
    "b": 255,
    "default_font": true
}
```

payload is this: `"Geschirrspüler: finished / noch 0 Minuten"`

But what I get are two big white blocks with a x2F in the middle  instead of the Dash. The Dash is a Glyph, i know, but it's availible in my font:
```
font:
  - file: CalciumThin.ttf
    id: default_font
    size: 16
    glyphs:  |
      !?"%‰()+*=,'-_.:°µ²³0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz€$@<>/
```

- used Hardware:
  - Ulanzi PixelClock

  - EspHoMaTriXv2, newest
