### ISSUE TITLE
[QUESTION] Remove/Change boot animation

### ISSUE THREAD

**Issue by popy2k14** [lubeda/EspHoMaTriXv2#203]
# Question

Sometimes my ulanzi's are rebooting and showing the fancy boot animation.
One is in a bedroom and i want to get rid of the boot animation.

There is a "boot_logo", but that's just showing a logo after boot, not what i want.

Is there such a feature?

## Additional information

- used Hardware:
  - ESP32
  - EspHoMaTriXv2 version: [e.g. 2023.7.0]

**Comment by lubeda** [comment]
Hi,
I don't know in detail, because i'm working on an upcoming release wich will be a bit different in details. But what about setting the boot_logo to all "0" (all pixels black) an calling the service

```yaml
service: esphome.ulanzi_bitmap_screen
data:
  icon: >-
   "[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,63519,63519,63519,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,31,0,0,0,0,0,0,0,0,0,63488,0,63488,0,0,0,63519,0,0,0,0,2016,2016,0,0,0,65514,0,65514,0,0,0,31,0,0,0,64512,0,0,64512,0,63488,63488,0,63488,63488,0,0,63519,63519,63519,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,31,31,31,0,0,0,64512,64512,0,0,63488,63488,63488,63488,63488,0,0,63519,0,0,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,31,0,0,0,0,64512,64512,0,0,0,63488,63488,63488,0,0,0,63519,63519,63519,63519,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,0,31,31,0,64512,0,0,64512,0,0,0,63488,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]" 
  lifetime: 2
  screen_time: 16
```

With the upcoming 2024.1.0 there will be a in build animation or a logo which you can choose as you wish.
