### ISSUE TITLE
Date color

### ISSUE THREAD

**Issue by pepe59** [lubeda/EspHoMaTriXv2#210]
I don't know if it's a bug but if I set the clock and date color, after 24 hours the time color is correct but the date color goes back to white.
I have to call service again and it's fine for another 24 hours.

```
service: esphome.ulanzi_set_clock_color
data:
  r: 255
  g: 140
  b: 0
```

**Comment by lubeda** [comment]
Hi, 
I think this is no bug. This is more like a hidden automatism. Try changing your YAML like this:

```yaml
on_empty_queue:
    then:
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,false,1);
          id(rgb8x32).icon_clock("calendar|day#0",1440,10,false,255,140,0);
```
So the clock color isn't overwritten by the default color.

**Comment by pepe59** [comment]
Yes, the clock color is not overridden by the default color.
Date only.
I am using the code from the ulanzi-easy.yaml documentation for the Ulanzi TC001 device.
If I add your recommended yaml to the end of ulanzi-easy.yaml

```
  on_next_screen:
    - homeassistant.event:
        event: esphome.new_screen
        data_template:
          iconname: !lambda "return icon.c_str();"
          text: !lambda "return text.c_str();"

  on_empty_queue:
    then:
      - lambda: |-
          id(rgb8x32).set_infotext_color(20,20,20,20,20,20,false,1);
          id(rgb8x32).icon_clock("calendar|day#0",1440,10,false,255,140,0);
```
an error occurs in the code
`[on_empty_queue] is an invalid option for [ehmtxv2]. Did you mean [allow_empty_screen]?`

**Comment by pepe59** [comment]
Installed as per documentation
```
external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: main
    refresh: 60s 
    components: [ ehmtxv2 ]   

esphome:
  comment: "EHMTXv2 from LuBeDa"
  name: $devicename 
  project:
    name: "Ulanzi.EHMTXv2"
    version: "2.0.0"
  on_boot:
    then:
      - ds1307.read_time:
```
