### ISSUE TITLE
Strapping GPIO15 prevents OTA flashing from working

### ISSUE THREAD

**Issue by noiob** [lubeda/EspHoMaTriXv2#212]
With the default easy_ulanzi.yaml I can't do OTA updates. They usually go through and the clock reboots but it doesn't actually change anything.

I have a fairly new Ulanzi smart clock (might be a newer hardware revision? maybe that's why it hasn't come up yet) and I've struggled to configure anything until I realized that the warning about GPIO15 being a boot selector pin was actually correct, removing the pin definition made OTA updates work again.

I'd propose just removing anything buzzer-related from the default config or at least adding a warning. I don't think not having the buzzer connected  is a big loss to anyone since it's pretty quiet and sounds awful.

## Important

If the buzzer config is removed, when rebooting the clock through the left+right button combo the buzzer never stops. This can be remedied without negative effect by using the following config:

```yaml
output:
  - platform: gpio
    pin:
      number: GPIO15
      ignore_strapping_warning: true
    id: buzzer_pin

esphome:
  on_boot:
    then:
      - lambda: id(buzzer_pin).turn_off();
```
