### ISSUE TITLE
[BUG] ESPhome 2024.6.1 Breaking Change: Update YAML File for OTA Fix

### ISSUE THREAD

**Issue by idodov** [lubeda/EspHoMaTriXv2#240]
In ESPhome 2024.6.1, there is a breaking change that requires updating the YAML file. To fix this, you need to add `platform: esphome` under the OTA section. This adjustment should address the issue.

```yaml
ota:
  password: !secret ota_password
  platform: esphome
```
