### ISSUE TITLE
[BUG] Broken icons on display

### ISSUE THREAD

**Issue by sophipl** [lubeda/EspHoMaTriXv2#260]
# Bug report
When I display the icons, they are broken
I recorder the issue displaying all icons:
https://www.youtube.com/watch?v=-OSxfgaY-6E

## Describe the bug

I have added screens for display from HomeAssistant and recorded what is displayed.
I'm using Ulanzi TC001 using `ulanzi-easy.yaml` configuration (adding the image and animations sections)
I tried tweaking the settings, nothing worked.
Generated html file with icons looks correct to me.
It feels to me that animation frames are correct, but the images themselves are broken, some contains colors not present in original icons, perhaps the problem with RGB565 reading?
Startup animation (extending box) and bootup logo is correct.
I'm new to ESPHOME.
Also sometimes I see crash from console I think on bootup only.

The device is new, I might have new revision, I needed to add `mode: INPUT_PULLUP` for other buttons to work, and device couldn't be flashed from website with tasmota at first, I used `esptool.py`, it complained that the device is not in BOOT stage.

## Additional information

- used Hardware:
  - Ulanzi TC001 ESP32-D0WD
  - EspHoMaTriXv2 version: master branch > 2024.12.0, I tried other versions too

## To Reproduce

Flash `ulanzi-easy.yaml` to the clock and attempt to display the icons after fixing missing sections

## Expected behavior

Proper icons should be displayed

## Screenshots

https://www.youtube.com/watch?v=-OSxfgaY-6E

## Logs

Might be unrelated, I think it happens on bootup sometimes.

```
Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x401836fc: 9890ef29 00000000 00000000
Core  0 register dump:
PC      : 0x40183701  PS      : 0x00060430  A0      : 0x8018330d  A1      : 0x3ffcda90  
A2      : 0x3ffde950  A3      : 0x00000001  A4      : 0x00000005  A5      : 0x00000020  
A6      : 0x3ffbfb90  A7      : 0x00060b23  A8      : 0x00000020  A9      : 0x00002009  
A10     : 0x00000001  A11     : 0x003fffff  A12     : 0x80084347  A13     : 0x3ffbd110  
A14     : 0x00000001  A15     : 0x3ffcc260  SAR     : 0x0000001b  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x40089ddc  LEND    : 0x40089df2  LCOUNT  : 0xffffffff  


Backtrace:0x401836fe:0x3ffcda900x4018330a:0x3ffcdab0 0x4018338a:0x3ffcdae0 0x40183551:0x3ffcdb00 0x401580f9:0x3ffcdb40 0x4015891b:0x3ffcdb70 0x4018479f:0x3ffcdbb0 
```

Some other warnings
```
[W][esp-idf:000]: E (228288) system_api: Base MAC address from BLK3 of EFUSE version error, version = 0
```

No new logs when requesting icon screens or displaying them

## Services calls

```yaml
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      screen_time: 4
      lifetime: 10
      icon_name: error
      text: error
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: home_assistant
      text: home_assistant
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: temperature
      text: temperature
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: lightbulb
      text: lightbulb
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: music
      text: music
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: phone
      text: phone
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_rainbow_icon_screen
    metadata: {}
    data:
      default_font: true
      icon_name: car
      text: car
      lifetime: 10
      screen_time: 4
  - action: esphome.tclock_full_screen
    metadata: {}
    data:
      icon_name: sleep8x32
      screen_time: 3
      lifetime: 10
mode: single
```
