### ISSUE TITLE
[BUG] No update due to missing glyphs in monobit.ttf

### ISSUE THREAD

**Issue by clfberlin** [lubeda/EspHoMaTriXv2#263]
Hi there. For some reason updates fail due to missing glyphs in monobit.ttf.
Any idea what changed?
```
Failed config

font: [source /config/esphome/ulanzi-archiv.yaml:76]
  
  Font monobit.ttf is missing 2 glyphs:
      
   (b'\\n')
      € (b'\\u20ac').
  - file: _fonts/monobit.ttf
    size: 16
    id: default_font
    glyphs: |-
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz@<>ß§€/
```
Seen in ESPhome on HomeAssistant
Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

Thanks and cheers

**Comment by lubeda** [comment]
hi,
i think it is the euro sign and the backslash at the end

**Comment by clfberlin** [comment]
Thanks. € is one of them. Couldn't locate the other yet. Odd that they are suddenly declared as missing.

**Comment by gzxto1** [comment]
Use that

```
font: 
  - file: ulanzi/font/monobit.ttf
    id: monobit_font
    size: 16
    glyphs: >-
      !?"%()+*=,-_.:°µ²³0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz$@<>/
```

make sure using `>-`
