### ISSUE TITLE
[BUG] Special font doesn't display.

### ISSUE THREAD

**Issue by darkpoet78** [lubeda/EspHoMaTriXv2#27]
# Bug report

My clock screen only uses the default_font instead of the special_font.

## Describe the bug

Worked as expected on develop branch right up to a few hours ago (just updated lol)... saw you push through an update so updated again... both on main and develop branches.   Only shows the time with default_font.

## Additional information

- used Hardware:
  - Ulanzi TC-001

## Configuration

```
font:
  - file: ehmtxv2/MatrixClock-Chunky8.bdf #
    id: special_font
    #size: 16
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:APMTapmt
  - file: ehmtxv2/MatrixClock-Light8.bdf #
    id: default_font
    #size: 16
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz°{|}~¡¢£¤¥¦§¨©ª«¬®¯±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ
```
