### ISSUE TITLE
No devices or entities in homeassistant (Solution)

### ISSUE THREAD

**Issue by s00500** [lubeda/EspHoMaTriXv2#270]
Hey everybody, just had a weird issue when updating that I could not get any device to show up in homeassistant, traced it down to be this ticket here:
https://github.com/esphome/issues/issues/6333

In my logs I found this error:

```
[14:17:57][D][esp-idf:000]: E (18089) system_api: Base MAC address from BLK3 of EFUSE version error, version = 0
```

my current fix for this is this one 

```
esp32:
  board: esp32dev
  framework:
    type: arduino
    advanced:
      ignore_efuse_custom_mac: true
```

Just putting this here in case somebody else has that problem....
