### ISSUE TITLE
[BUG] ICON_SCREEN bottom line of text not shown

### ISSUE THREAD

**Issue by nouser2013** [lubeda/EspHoMaTriXv2#294]
# Bug report

## Describe the bug

If I have a text with a font which needs to write pixels to the last line of the PixelClock, this line is not shown. See attached picture, the German word `Mässig` has its `g` (lower case) truncated at the bottom.

## Additional information

- used Hardware:
  - ESP32
  - EspHoMaTriXv2 version: `2025.5.2`

## To Reproduce

- Use the indicated version of EspHoMaTrixV2
- See configuration below.
- Schedule an ICON_SCREEN with Text stretched across all 8 pixels, either:
  - with a lower case character, or
  - with an uppercase character when the font takes all 8 pixels for those

## Expected behavior

Text should be shown over the full display height.

## Configuration

```yaml
# [...]
font:
  - file: fonts/MatrixLight8.bdf
    id: default_font
    glyphs:  |-
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ[\]^_`abcdefghijklmnopqrstuvwxyzäöüß°
  - file: fonts/MatrixChunky6.bdf
    id: special_font
    glyphs: |-
      ! "#$%&'()*+,-./0123456789:APMTapmt
display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (y % 2 == 0) {
        return (y * 32) + x;
      }
      return (y * 32) + (31 - x);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  show_seconds: false
  show_dow: true
  blend_steps: 0
  week_start_monday: true
  scroll_small_text: false
  vertical_scroll: false
  default_font_id: default_font
  default_font_yoffset: 8
  special_font_id: special_font
  special_font_yoffset: 6
  multicolor_text: true
  scroll_count: 1 
  scroll_interval: 32
  icons: 
    - id: error
      lameid: 26465
  # [...]
# [...]
```

## Screenshots

![Image](https://github.com/user-attachments/assets/6c2c2e26-8621-45d2-9d2b-7c33b5c44106)
