### ISSUE TITLE
[BUG] Scroll time for long text not calculated correctly on ICON_SCREEN (?)

### ISSUE THREAD

**Issue by nouser2013** [lubeda/EspHoMaTriXv2#295]
# Bug report

## Describe the bug

Through HomeAssistant, I schedule `ICON_SCREEN`s that display texts of different lengths. Sometimes, those texts are very short and fit on the display (no problem), but when they exceed the 6 char limit, the scrolling becomes somewhat nondeterministic.

> [!NOTE]
> * I use `32ms` (`16ms` update delay `*` `2`) `scroll_interval`, *not* the default (?) `80ms`.
> * The scroll_count is set to 1

In my understanding, any text that exceeds the 6 chars limit, should now be scrolled through exactly once.

But if I schedule the screen with 3s `screen_time`:
* Text `Gut (12)` gets scrolled 1,5 times.
* Text `Ausreichend (201)` gets scrolled 0,98 times, the last brace is only half visible.
* Text `Extrem schlecht (350)` gets scrolled 0,6 times, the text is truncated.

## Additional information

- used Hardware:
  - ESP32
  - EspHoMaTriXv2 version: `2025.5.2`

## To Reproduce

See bug description.

## Expected behavior

Each text should be scrolled exactly the number of `scroll_count`, regardless of `screen_time` of each call.

> [!NOTE]
> I'm down, however, to accept that for small texts a scroll can be triggered again up to `screen_time` seconds. In this case, I'd simply decrease the `screen_time` to `1s`.

## Configuration

```yaml
# [...]
font:
  - file: fonts/MatrixLight8.bdf
    id: default_font
    glyphs:  |-
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ[\]^_`abcdefghijklmnopqrstuvwxyzäöüß°
  - file: fonts/MatrixChunky6.bdf
    id: special_font
    glyphs: |-
      ! "#$%&'()*+,-./0123456789:APMTapmt
display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (y % 2 == 0) {
        return (y * 32) + x;
      }
      return (y * 32) + (31 - x);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  show_seconds: false
  show_dow: true
  blend_steps: 0
  week_start_monday: true
  scroll_small_text: false
  vertical_scroll: false
  default_font_id: default_font
  default_font_yoffset: 8
  special_font_id: special_font
  special_font_yoffset: 6
  multicolor_text: true
  scroll_count: 1 
  scroll_interval: 32
  icons: 
    - id: error
      lameid: 26465
  # [...]
# [...]
```

## Services calls

```yaml
      - action: esphome.pixelclock_1_icon_screen
        continue_on_error: true
        metadata: {}
        data:
          default_font: true
          text: "Extrem schlecht (360)"
          icon_name: "iaq_extreme|iaq"
          screen_time: 3
          lifetime: 60
          r: 255
          g: 255
          b: 255
```
