### ISSUE TITLE
[BUG] Error updating - 2025.6.0 - type not specified

### ISSUE THREAD

**Issue by clfberlin** [lubeda/EspHoMaTriXv2#301]
Update is refused for 2025.6.0.
It aborts with
**Failed config**

```
esp32: [source /config/esphome/ulanzi-eg.yaml:52]
  board: esp32dev
```
and
**type not specified**
which refers to
```
  framework:
    advanced:
        ignore_efuse_custom_mac: true
```
I tried 2025.5.1 as ref

```
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: 2025.5.1
```
Thanks and cheers

**Comment by lubeda** [comment]
Can you provide a full log or screen shot? 

Does 2025.5.1 work with your yaml?

Which version of esphome are you using?

**Comment by clfberlin** [comment]
Hi @lubeda 
The full process when trying to update is pretty short:

```
INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/ulanzi-eg.yaml...
INFO Updating https://github.com/lubeda/EspHoMaTriXv2@2025.5.1
WARNING 
WARNING Please check the documentation and wiki https://github.com/lubeda/EspHoMaTriXv2
WARNING 
Failed config

esp32: [source /config/esphome/ulanzi-eg.yaml:52]
  board: esp32dev
  
  type not specified!.
  framework: 
    advanced: 
      ignore_efuse_custom_mac: True
```
My initial entry was

```
external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: 2025.2.0
    refresh: 60s 
    components: [ ehmtxv2 ]
```

I just replaced 2025.2.0 with 2025.5.1 for test purposes.
This error came up just after I updated ESPHome Builder to 2025.6.0
Thanks and cheers

**Comment by clfberlin** [comment]
PS: When I exclude 
```
#  framework: 
#    advanced: 
#      ignore_efuse_custom_mac: True
```
The update will go through. But that wil likely cause the old issue with device-mixups. I have 3 Ulanzis running.

**Comment by clfberlin** [comment]
Yes, indeed. Udate endet with
```
[23:39:15][W][esp-idf:000]: E (6325) system_api: Base MAC address from BLK3 of EFUSE version error, version = 0
[23:39:15][W][esp-idf:000]: E (6394) system_api: Base MAC address from BLK3 of EFUSE version error, version = 0
```

**Comment by clfberlin** [comment]
Update: Just adding 'type: arduino' under 'framework:' seems to solve it.
Worked with my Ulanzi. It updated properly and is back to life after reloading.

```
esp32:
  board: "$board"
  framework:
    type: arduino
    advanced:
      ignore_efuse_custom_mac: true
```
Thanks and cheers
