### ISSUE TITLE
rainbow_icon_screen service shows wrong icon

### ISSUE THREAD

**Issue by skgsergio** [lubeda/EspHoMaTriXv2#4]
I'm calling the service as follows and it is showing the first icon that I have configured (`ha`) and not the `calendar` one:

```yaml
service: esphome.pixel_clock_rainbow_icon_screen
data:
  default_font: false
  icon_name: calendar
  text: test
  lifetime: 1
  screen_time: 1
```

However `icon_screen` service works correctly:

```yaml
service: esphome.pixel_clock_icon_screen
data:
  default_font: false
  icon_name: calendar
  text: test
  lifetime: 1
  screen_time: 1
  r: 200
  g: 200
  b: 200
```

My icons:

```yaml
  icons:
    - id: ha
      lameid: 7956
    - id: tempc
      lameid: 2422
    - id: plug
      lameid: 403
    - id: humidity
      lameid: 51764
    - id: co2
      lameid: 30662
    - id: calendar
      lameid: 12345
```
