### ISSUE TITLE
My two custom fonts

### ISSUE THREAD

**Issue by dbuezas** [lubeda/EspHoMaTriXv2#63]
I wanted to use the full height of the display and maximize the number of chars in the screen so I made these two fonts.

I am really happy with the result, so dropping them here in case they can help someone else too :) 

![Kapture 2023-07-20 at 10 54 13](https://github.com/lubeda/EspHoMaTriXv2/assets/777196/730d3977-e170-4819-a0f5-94685ec21f17)

[CalciumSuperThinTall.ttf.zip](https://github.com/lubeda/EspHoMaTriXv2/files/12104023/CalciumSuperThinTall.ttf.zip)
[CalciumThinTall.ttf.zip](https://github.com/lubeda/EspHoMaTriXv2/files/12104024/CalciumThinTall.ttf.zip)

```yaml
ehmtxv2:
   ...
  default_font_yoffset: 8
  default_font_id: default_font
  special_font_yoffset: 8
  special_font_id: special_font
font:
  - file: rgb-clock/CalciumThinTall.ttf
    size: 16
    id: default_font
    glyphs: |
      !?"%‰()+*=,-_.:°µ²³0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz€$@<>/
  - file: rgb-clock/CalciumSuperThinTall.ttf
    size: 16
    id: special_font
    glyphs: |
      !?"%‰()+*=,-_.:°µ²³0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz€$@<>/
```
