### ISSUE TITLE
Show date

### ISSUE THREAD

**Issue by idodov** [lubeda/EspHoMaTriXv2#7]
Please return back the function that support not showing the date card as defualt (show_date: false).

**Comment by lubeda** [comment]
Hi, 

there is another way to remove the date display:

The date display is a screen in the queue, you can remove it in the YAML:
```
esphome:
  name: $devicename 
  on_boot:
    then: 
      - delay: 30s
      - lambda: |-
          id(rgb8x32)->del_screen("*",3);
```
or via service call:
```
service: esphome.ulanzi_del_screen
data:
  icon_name: "*"
  mode: 3
```

If you want a blank screen use:

```
service: esphome.esp32mic_blank_screen
data:
  lifetime: 1440
  screen_time: 10
```
