### ISSUE TITLE
[BUG] Bootloop

### ISSUE THREAD

**Issue by TheGroundZero** [lubeda/EspHoMaTriXv2#71]
# Bug report

## Describe the bug

I flashed a Ulanzi Pixel clock that used to run the v1 code with the latest YAML version of this v2 and now it enters a bootloop.

## Additional information

- used Hardware:
  - ESP32 (Ulanzi TC001 Pixel Clock)
  - EspHoMaTriXv2 version: 2023.7.0
  - ESPHome version: 2023.7.1

## To Reproduce

Copy YAML example and files according to documentation and flash device.

## Expected behavior

Clockface to display time and date like it used to in older versions

## Configuration

Based on https://github.com/lubeda/EspHoMaTriXv2/blob/main/copy2esphome/ulanzi-easy.yaml (with fixed font name)

```yaml
substitutions:
  devicename: ulanzi-tc001-d67068
  comment: "Ulanzi TC001 d6:70:68"
  board: esp32dev
  # Pin definition from https://github.com/aptonline/PixelIt_Ulanzi
  battery_pin: GPIO34
  buzzer_pin: GPIO15
  ldr_pin: GPIO35
  matrix_pin: GPIO32
  left_button_pin: GPIO26
  mid_button_pin: GPIO27
  right_button_pin: GPIO14
  scl_pin: GPIO22
  sda_pin: GPIO21

esp32:
  board: esp32dev

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EspHoMaTriXv2
      ref: main
    refresh: 60s 
    components: [ ehmtxv2 ]   

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret not_domain
  use_address: 192.168.70.67

esphome:
  comment: $comment
  name: $devicename 
  project:
    name: "Ulanzi.EHMTXv2"
    version: "2.0.0"
  on_boot:
    then:
      - ds1307.read_time:

ota:

logger:
  level: WARN

api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: tune
      variables:
        tune: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return tune;'

web_server:

globals:
  # aab = auto-adjustable brightness
  - id: aab_enable
    type: "bool"
    restore_value: true
    initial_value: "true"
  - id: aab_add
    type: int
    initial_value: '10'
  - id: aab_max
    type: int
    initial_value: '220'
  - id: aab_min
    type: int
    initial_value: '20'

i2c:
  sda: $sda_pin
  scl: $scl_pin
  scan: true
  id: i2cbus
    
time:
  - platform: homeassistant
    timezone: Europe/Brussels
    on_time_sync:
      then:
        ds1307.write_time:
  - platform: ds1307
    update_interval: never
    id: ehmtx_time

image:
   - file: images/1pixel.gif
     id: breaking20237

animation:
  - file: images/1pixel.gif
    id: breaking202371

output:
  - platform: ledc
    pin: $buzzer_pin
    id: rtttl_out

rtttl:
  output: rtttl_out

font:
  - file: fonts/mateine.ttf
    size: 16
    id: default_font
    glyphs:  |
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz@<>ß§€/

display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (y % 2 == 0) {
        return (y * 32) + x;
      }
      return (y * 32) + (31 - x);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
      
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: "%H:%M"
  date_format: "%d.%m."
  show_seconds: false
  default_font_id: default_font
  special_font_id: default_font 
  boot_logo: "[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,63519,63519,63519,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,31,0,0,0,0,0,0,0,0,0,63488,0,63488,0,0,0,63519,0,0,0,0,2016,2016,0,0,0,65514,0,65514,0,0,0,31,0,0,0,64512,0,0,64512,0,63488,63488,0,63488,63488,0,0,63519,63519,63519,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,31,31,31,0,0,0,64512,64512,0,0,63488,63488,63488,63488,63488,0,0,63519,0,0,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,31,0,0,0,0,64512,64512,0,0,0,63488,63488,63488,0,0,0,63519,63519,63519,63519,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,0,31,31,0,64512,0,0,64512,0,0,0,63488,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]"
  icons: 
    - id: error
      lameid: 40530
    - id: home_assistant
      lameid: 47693
    - id: temperature
      lameid: 2056
    - id: lightbulb
      lameid: 1762
    - id: music
      lameid: 45625
    - id: phone
      lameid: 1232
    - id: car
      lameid: 2819
    - id: sleep8x32
      url: https://user-images.githubusercontent.com/16407309/224850723-634c9b2d-55d9-44f2-9f93-765c0485b090.gif 
  on_next_screen:
    - homeassistant.event:
        event: esphome.new_screen
        data_template:
          iconname: !lambda "return icon.c_str();"
          text: !lambda "return text.c_str();"

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    internal: true
    variant: WS2812
    pin: $matrix_pin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    gamma_correct: 2.0
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
  
binary_sensor:
  - platform: status
    name: "$devicename Status"
  - platform: gpio
    pin:
      number: $left_button_pin
      inverted: true
    name: "Left button"
  - platform: gpio
    pin: 
      inverted: true
      number: $mid_button_pin
      mode: INPUT_PULLUP
    name: "Middle button"
  - platform: gpio
    pin: 
      number: $right_button_pin
      inverted: true
    name: "Right button"

sensor:
  - platform: sht3xd
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Relative Humidity"
    update_interval: 60s
  - platform: adc
    pin: $battery_pin
    name: "$devicename Battery"
    id: battery_voltage
    update_interval: 10s
    device_class: battery
    accuracy_decimals: 0
    attenuation: auto
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
      - multiply: 1.6
      - lambda: |-
          auto r = ((x - 3) / 0.69 * 100.00);
          if (r >= 100) return 100;
          if (r > 0) return r;
          if (r <= 0) return 1;
          return 0;
    unit_of_measurement: '%'
  - platform: adc
    id: light_sensor
    name: "$devicename Illuminance"
    pin: $ldr_pin
    update_interval: 10s
    attenuation: auto
    unit_of_measurement: lx
    device_class: illuminance
    accuracy_decimals: 0
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 - 15 ;
    on_value:
      then:
        - lambda: |-
            if ( id(aab_enable) ) {
              int n = x / 4 + id(aab_add); // new_value
              if (n > id(aab_max)) n = id(aab_max);
              if (n < id(aab_min)) n = id(aab_min);
              int c = id(rgb8x32)->get_brightness(); // current value
              c = c>0?c:1 ; 
              int d = (n - c) * 100 / c; // diff in %
              if ( abs(d) > 2 ) id(rgb8x32)->set_brightness(n);
            }

switch:
  - platform: template
    name: "Auto-Adjust Brightness"
    id: switch_autobrightness
    icon: mdi:brightness-auto
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      if (id(aab_enable)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      lambda: |-
        id(aab_enable) = true;
    turn_off_action:
      lambda: |-
        id(aab_enable) = false;
```

## Screenshots

![image](https://github.com/lubeda/EspHoMaTriXv2/assets/2406013/cff773e1-bae9-4a1b-8a62-682455ac8c6b)

## Logs

```text
fbFacB!�B	a�aB�B�R�!!)a
cc�c7Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
[E][ota:476]: Boot loop detected. Proceeding to safe mode.
[W][wifi:609]: WiFi Unknown connection status 0
[W][wifi:552]: Incomplete connection.
[W][wifi_esp32:504]: Event: Disconnected ssid='***' bssid=[redacted] reason='Association Leave'
[W][wifi_esp32:504]: Event: Disconnected ssid='***' bssid=[redacted] reason='Association Leave'
[W][wifi:609]: WiFi Unknown connection status 0
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
[E][ota:481]: No OTA attempt made, restarting.
[W][wifi_esp32:504]: Event: Disconnected ssid='***' bssid=[redacted] reason='Association Leave'
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060830  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da44c  PS      : 0x00060a30  A0      : 0x800efa13  A1      : 0x3ffb26d0  
A2      : 0xffffffff  A3      : 0x437f0000  A4      : 0x00000020  A5      : 0x00000008  
A6      : 0x00000010  A7      : 0x00000082  A8      : 0x00000200  A9      : 0x3ffb26b0  
A10     : 0x00000050  A11     : 0x437f0000  A12     : 0x3ffb44d9  A13     : 0x3ffb44d0  
A14     : 0x00000010  A15     : 0x00000003  SAR     : 0x00000006  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000218  LBEG    : 0x40089e98  LEND    : 0x40089eae  LCOUNT  : 0xffffffff  


Backtrace:0x400da449:0x3ffb26d00x400efa10:0x3ffb26f0 0x400fdfce:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
[E][ota:476]: Boot loop detected. Proceeding to safe mode.
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
[W][ota:103]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
```

## Services calls

```text
(optional) The YAML of your service calls
```
