### ISSUE TITLE
[BUG] Example code font too big, text chopped off

### ISSUE THREAD

**Issue by TheGroundZero** [lubeda/EspHoMaTriXv2#72]
# Bug report

## Describe the bug

The top of the time and date is chopped off on the Ulanzi TC001.
Either the font is too big or the font size is set too big in the example yaml. Or there's an error in the pixel mapper.

## Additional information

- used Hardware:
  - Ulanzi TC001
  - EspHoMaTriXv2 version 2023.7.0

## To Reproduce

- Copy example code and flash it to the Ulanzi TC001 pixel clock

## Expected behavior

All text should be readable

## Configuration

```yaml
# ...
font:
  - file: fonts/mateine.ttf
    size: 16
    id: default_font
    glyphs:  |
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz@<>ß§€/
# ...
```

## Screenshots

![image](https://github.com/lubeda/EspHoMaTriXv2/assets/2406013/73a76e8e-4223-4495-8ff0-d72df3736af2)
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/2406013/1dfaf079-8e78-424d-80b9-7a1b1dd0205e)
