### ISSUE TITLE
[FEATURE REQUEST] Add a screen identifier (not by icon name, but unique)

### ISSUE THREAD

**Issue by andrewjswan** [lubeda/EspHoMaTriXv2#83]
# Feature Request

### Is your feature request related to a problem?

Failure to display two screens with different meanings but the same icons, for example current weather and weather forecast.
We have a limited number of icons, so sharing icons with different name is not feasible.

### Describe the solution / feature you'd like

Add `screen_name` to `icon_screen`, `rainbow_icon_screen` services, if `screen_name` is specified it is used for screen identification, if not specified it takes the value of `icon_name` field.
In the services `del_screen`, `force_screen` replace the `icon_name` parameter with `screen_name` (or leave it as it is, but search for screen by the screen_name parameter), to accurately identification the screen.

If make these changes, then it will be possible to display different data with the same icons, for example, the current weather, and the weather forecast for tomorrow.

**Comment by trip5** [comment]
This might be a similar reply as I made to the other post...  Try making multiple IDs that refer to the same icon.  ESPHome compresses the files anyway so duplicate files would not take up much extra flash size.

It'd be an easy way to see if you can find out if the actual limit is 90 anyways.

**Comment by andrewjswan** [comment]
In my opinion, linking to the icon name is not a good option, but adding a screen name is both more flexible and logical

**Comment by lubeda** [comment]
In my opinion the icon name is the best way. Why should I use two different values with the same icon? How can I distinguish between the two values?
I need a detailed example to judge your request.

**Comment by andrewjswan** [comment]
`icon_name`: icon that is displayed
`screen_name`: screen identifier

There is no problem with finding the right icon and the right screen because if only `icon_name` is specified in the call then `screen_name` will take its value, if both values are specified then each will have its own value.

This will allow to display the `current weather` on one screen and the `weather forecast` on the second screen. The icons can be the same, for example `sunny`, but `screen_name` we can specify different `weather` and `forecast`. 
And it will allow to update the data not to delete the screen, but just update it by `screen_name`.

**Comment by andrewjswan** [comment]
Old way:
```
      - service: esphome.esp_pixel_clock_del_screen
        data:
          icon_name: weather_*
          mode: 5
      - service: esphome.esp_pixel_clock_icon_screen
        data:
          icon_name: "weather_{{ states('weather.current_weather') | replace('-','_') }}"
          text: "{{ states('sensor.temperature_outside') }}°C"
          lifetime: 320
          screen_time: 10
          default_font: false
          r: 200
          g: 200
          b: 200
```
New way:
```
      - service: esphome.esp_pixel_clock_icon_screen
        data:
          icon_name: "weather_{{ states('weather.current_weather') | replace('-','_') }}"
          screen_name: weather
          text: "{{ states('sensor.temperature_outside') }}°C"
          lifetime: 320
          screen_time: 10
          default_font: false
          r: 200
          g: 200
          b: 200
      - service: esphome.esp_pixel_clock_icon_screen
        data:
          icon_name: "weather_{{ states('weather.forecast_weather') | replace('-','_') }}"
          screen_name: forecast
          text: "{{ states('sensor.temperature_forecast') }}°C"
          lifetime: 320
          screen_time: 10
          default_font: false
          r: 200
          g: 200
          b: 200
```
