### ISSUE TITLE
[QUESTION] Automatic translation of characters

### ISSUE THREAD

**Issue by trip5** [lubeda/EspHoMaTriXv2#87]
Ah, I was digging around the ehmtxv2 files and I saw what you meant when you said "automatic translation of characters" over at https://github.com/trip5/Matrix-Fonts/issues/3

In the extended_state.yaml I see:

````
    darkpoet78_replace:
      name: Use special character provided by Trip5 fonts (default=false)
      description: If you are using the bdf fonts of https://github.com/trip5/Matrix-Fonts you have to translate some character e.g. the euro sign. This flag actives the translation.
      selector:
        boolean:
      default: false
````

The intention was to allow these characters be substituted "on the fly" by the firmware. So I checked the .h and .cpp files and the idea was never implemented, right?

Now I've figured out how to properly implement TTF bitmap files and I'm even working on a Cyrillic character set.  How about just removing that section from the yaml completely?  It's totally possible to use Unicode characters when using my Matrix-Fonts TTF files.
