### ISSUE TITLE
[FEATURE REQUEST] Add a graph display screen

### ISSUE THREAD

**Issue by andrewjswan** [lubeda/EspHoMaTriXv2#90]
# Feature Request

### Describe the solution / feature you'd like

Add a graph display screen, in the configuration we specify the graph, pass the graph ID to the EspHoMaTriXv2 component, and when needed, the user will call the graph screen display service, indicating its lifecycle and indicating the rebound time, perhaps another color. 
The graph will be displayed on the screen from time to time.

### Additional context

```
graph:
  - id: single_temperature_graph
    sensor: temp_outside
    duration: 64h
    border: false
    width: 32
    height: 8
    line_thickness: 1
```

```
ehmtxv2:
  id: rgb8x32
  graph_component: single_temperature_graph
  ...
```

API:
```
show_graph => => {"lifetime", "screen_time"}
show_graph_color => => {"lifetime", "screen_time", "rgb"}
```
Service
```
void show_graph (int =D_LIFETIME, int screen_time=D_SCREEN_TIME);
void show_graph_color (int =D_LIFETIME, int screen_time=D_SCREEN_TIME, RGB);
```

![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/8ea95393-fdc3-41fc-a47b-c3cbeedb8fbf)

**Comment by andrewjswan** [comment]
```
      case MODE_GRAPH_SCREEN::
        color_ = this->text_color; // or Graph Color or ...
        this->config_->display->it.graph(0, 0, id(graph_component: single_temperature_graph), color_);
        break;
```

**Comment by malinovsku** [comment]
I support the idea! What about multiple graphs? The identifiers for the difference are already there. As an example, show different sensors under different conditions. 
Can you still consider the option of an icon with a graph? By name, icon_graph is possible. So it will be possible to distinguish between graphs or some additional information to the graph

**Comment by andrewjswan** [comment]
I think it is also not difficult to realize, not to bind one chart ID in ehmtxv2 configuration, but to declare in ESPHome the necessary charts, and when calling a service or API to specify the necessary chart ID. 
```
show_graph =>{"graph_id", "lifetime", "screen_time"}
```
It is also possible to output it with an icon, but then it will be necessary to define the graph as 8x24 and pass the icon name when calling it.
```
show_graph =>{"iconanme", "graph_id", "lifetime", "screen_time"}
```
Like:
```
graph:
  - id: single_temperature_graph
    sensor: temp_outside
    duration: 64h
    border: false
    width: 24 or 23
    height: 8
    line_thickness: 1
```

```
show_graph =>{"temp", "temp_outside", "5", "5"}
```
