### ISSUE TITLE
[FEATURE REQUEST] A screen with an icon and data displayed on it.

### ISSUE THREAD

**Issue by andrewjswan** [lubeda/EspHoMaTriXv2#92]
# Feature Request

### Describe the solution / feature you'd like

I've already displayed the concept in another Issue, but I'll move it here.

Add a family of screens that could display some limited data like day of the week, day of the month, on an icon that works as a carpet pad. 

For example:
- icon_time - display: icon and time, like weather and time
- icon_time_data - display: icon and time, like calendar icon, day or weekday on icon and time
- icon_date - display: icon and date, like weather and time
- icon_date_data - display: icon and date, like calendar icon, day or weekday on icon and time

Generate a window identifier for each screen, then you can have identical sets displaying different information, like:
- weather - time
- day - time
- weekday - data
- weather - temperature

Also add the ability to specify a starting set of screens), e.g. `icon_time with day` icon_date_with_weekday`

### Additional context

Сoncept:
https://github.com/lubeda/EspHoMaTriXv2/issues/85#issuecomment-1738627157

**Comment by malinovsku** [comment]
@andrewjswan Thanks! I tested the display with this icon, and it seems that it would be better to omit a number or a word, since it is strongly pressed to the top. There are also doubts about the gaps in both days and days of the week. maybe in the config it is possible to specify which format to show? Since opinions may be divided. Options on the screenshots
![Снимок экрана 2023-10-05 в 01 15 40](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/61cc5ed0-3880-4043-85f5-d4ce350d37d5)
![Снимок экрана 2023-10-05 в 01 10 04](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/4eb35e21-25df-48a4-8133-42bb76c3c12e)
![Снимок экрана 2023-10-05 в 01 09 35](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/aa6972b7-5dfb-456c-8025-f3342df0d314)
![Снимок экрана 2023-10-05 в 01 09 14](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/7b414b16-eb5a-4018-802d-5f7a50df017d)
![Снимок экрана 2023-10-05 в 01 08 37](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/8946c51c-3c0c-4462-a0fa-c89edc238094)

**Comment by andrewjswan** [comment]
> since it is strongly pressed to the top

The baseline specified in the config for the selected font is used for output, i.e. the information on the icon is on the same bottom line as the font displayed on the right. The easiest solution is to specify 7(8) as the baseline, then the information on the icon will be displayed starting from the second bottom line, the way is more complicated is to get the font metric, get its width and height, and according to it output the text. 
I will try both options, see how it will be better and easier.


> There are also doubts about the gaps in both days and days of the week. maybe in the config it is possible to specify which format to show?

Well, the usual, simple, `crutchy way` I can do it. The smart way is to pass the display format and store it, I don't know what is better, but let's start with `crutches`. :) Let's use a pipe `|` :)

**Comment by andrewjswan** [comment]
Mode added ...
- icon|day#mode
- icon|weekday#mode
mode:
- 0 - default - left and right - baseline from font
- 1 - center - baseline from font
- 2 - center - right - baseline from font
- 3 - left and right - baseline 7
- 4 - center - baseline 7
- 5 - center - right - baseline 7
https://github.com/andrewjswan/EspHoMaTriXv2/commit/4949ceeb58535b004ef2fe4272191ed1c2d9e5b6

**Comment by andrewjswan** [comment]
@malinovsku @lubeda 
I think this is the best option. 
I just need to add the ability to set 2 colors, or separately for days and days of the week, i.e. 4.
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/438747dd-d3bd-4d73-b74a-45c765338e7e)

**Comment by andrewjswan** [comment]
`set_infotext_color` added ...

**Comment by andrewjswan** [comment]
Tested it yesterday, not all bad but not all good either. 
Different fonts bring a lot of variety, especially letters, each font has its own base line, width, height, and it is difficult to calculate and correctly fit into a **matrix 8x8**, I added `info_text_yoffset` to specify the base line for displaying information on the icon. I also redid the display modes. 
I'll check how it works and make a PR.

**Comment by andrewjswan** [comment]
For now, the current display modes:
Default:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/3465f4c9-761f-4f91-a24d-719beff96ff4)
Mode 1:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/e2050df7-b796-4c86-bfc9-39cca2b770ba)
Mode 2:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/67d3ae63-9961-4a42-95be-be855ce40baa)
Mode 3:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/13082f75-5c22-4953-a70d-f36b79a15008)
Mode 4:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/b39e27db-c7ca-41c1-abea-94328813516d)

**Comment by andrewjswan** [comment]
Although, I see Igor did it through functions, maybe that's more correct, I'll follow that way. I will make changes in my new code and check it.
https://github.com/lubeda/EspHoMaTriXv2/commit/fbdb8feb0d8f1a5d93076d10e959141ca658b441

**Comment by andrewjswan** [comment]
Look like all work fine...
![IMG_20231006_181149](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/31d3d64e-8cca-40c1-9184-c449f7da2e07)
![IMG_20231006_181202](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/ebfe8d7c-147b-44bf-b3d0-21e210c287d8)
![IMG_20231006_181205](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/7decb2cc-7b51-40cb-83d8-c479ad84adbc)
![IMG_20231006_181211](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/6fed0465-d2eb-4e94-a505-f7d9f6d48ebc)
![IMG_20231006_181217](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/784bb77c-ec81-4553-b2f6-daa3e920d8ec)
![IMG_20231006_181224](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/335b2c8f-fb58-4444-995d-d28b4ecfdb7b)

**Comment by andrewjswan** [comment]
Test scrypt:
```yaml
script:
  pixel_clock_test:
    alias: "Pixel Clock - Test"
    sequence:
      - service: esphome.pixel_clock_set_infotext_color
        data:
          left_r: 50
          left_g: 50
          left_b: 50
          right_r: 50
          right_g: 50
          right_b: 240
          default_font: true
          y_offset: 1

      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|day
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 240
          g: 0
          b: 0
      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|day#1
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 0
          g: 240
          b: 0
      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|day#2
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 0
          g: 0
          b: 240
      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|day#3
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 240
          g: 240
          b: 240
      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|day#4
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 240
          g: 240
          b: 240

      - service: esphome.pixel_clock_icon_date
        data:
          icon_name: calendar|weekday
          lifetime: 1
          screen_time: 5
          default_font: true
          r: 240
          g: 0
          b: 240
```
